### PR TITLE
chore(setup Coveralls): Intergrate coverage and coveralls

### PR DESCRIPTION
**Pull request by Etomovich**
**Description**
<hr />
This PR adds coveralls to the project. It also excludes pre-generated files from the coverage report specifically serviceWorker.js
<br/><br/>

**Type of Change**
<hr />

- [x] chore(non-breaking change that allows correct coverage report to be generated and incorporate coveralls in the project).
<br/>

**Checklist**
<hr />

- [x] Add coveralls in the project for checking test coverage.
- [x] Remove all files that are auto-generated from the coverage.
<br/>

**Related Stories**
<hr />

[Add Coveralls](https://www.pivotaltracker.com/n/projects/2313280/stories/165244165)

### CODE REVIEW

**Review by ElMonstro — APPROVED** [review]
Coveralls has been installed and the coverage check has been added, It works.

**Comment by MandelaK** [comment]
How can we get coverage locally? I believe we were supposed to be able to get that too somehow

**Comment by Etomovich** [comment]
> How can we get coverage locally? I believe we were supposed to be able to get that too somehow

@MandelaK I think `npm run coverage` will work since I have configured coverage in the package.json file under `scripts`

**Review by abulojoshua1 — APPROVED** [review]
LGTM

**Pull request merged**
