### PR TITLE
chore (setup sass): Setup sass compilation to css

### PR DESCRIPTION
**Pull request by cob04**
**Description**

This **PR** adds `sass` support to the project 
- It installs the package `node-sass`
- Renames `.css` files to `.scss`
- Imports and uses `index.scss` in `index.js`

<hr>
**Type of change**

- [x] chore(breaking change which adds sass support).

<hr>

**How to test this manually**
- Clone the repository `https://github.com/andela/ah-legion-frontend`
- Checkout the branch `ch-setup-sass-164046206`
- Write `sass` styles in  `.scss` files
-  Run `npm run build`
- Notice the `.scss` files are compiled to `css` in the build folder.

**Checklist:**
- [x] This follows all the guidelines for this project.

#### Related Stories

[#164046267](https://www.pivotaltracker.com/story/show/164046206)

### CODE REVIEW

**Review by ElMonstro — APPROVED** [review]
Only relevant files are changed. Approved

**Comment by abulojoshua1** [comment]
@cob04, kindly update the readme on how to use sass in the project.

**Comment by cob04** [comment]
> @cob04, kindly update the readme on how to use sass in the project.

will do.

**Review by BrianSerem — APPROVED** [review]

**Review by MandelaK — APPROVED** [review]

**Review by RachelleMaina — APPROVED** [review]
LGTM

**Comment by cob04** [comment]
> @cob04, kindly update the readme on how to use sass in the project.

I'm done, please review.

**Review by abulojoshua1 — APPROVED** [review]
LGTM

**Pull request merged**
